leads/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("survey.urls")),
]

survey/urls.py
from django.urls import path

from .views import HomePageView, QuizView, analyze


app_name = "survey"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("quiz/", QuizView.as_view(), name="quiz"),
    path("survey/insights/", analyze, name="insights"),
]

survey/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, EmailValidator


class Lead(models.Model):
    email = models.EmailField(unique=True, validators=[EmailValidator()])
    score = models.IntegerField(
        default=0,
        blank=True,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(0),
        ],
    )

    def __str__(self):
        return f"{self.email}: {self.score} points"


class Survey(models.Model):
    lead = models.OneToOneField(Lead, on_delete=models.CASCADE, null=True)

    def get_lead(self):
        return self.lead.email

    def get_questions(self):
        return self.questions.all()

    def __str__(self):
        return self.lead.email


class Question(models.Model):
    TYPES = [
        ("D", "Descriptive"),
        ("S", "Single Choice"),
        ("M", "Multiple Choice"),
    ]
    type = models.CharField(max_length=1, choices=TYPES)
    number = models.PositiveIntegerField(unique=True, null=True)
    text = models.CharField(max_length=255)

    def get_answer_options(self):
        if self.type != "D":
            options = Answer.objects.filter(question=self.pk).all()
            return options
        else:
            return None

    def __str__(self):
        return self.text


class Response(models.Model):
    survey = models.ForeignKey(
        Survey, on_delete=models.CASCADE, related_name="survey_responses"
    )
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="question_responses"
    )
    text = models.CharField(max_length=510)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )
    text = models.CharField(max_length=510, default="", blank=True)

    def __str__(self):
        return self.text

survey/views.py
import plotly.graph_objs as go
import plotly.offline as pyo
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.db import IntegrityError
from django.contrib.admin.views.decorators import staff_member_required

from . import utils
from .models import Lead, Survey, Response, Question


class HomePageView(TemplateView):
    template_name = "home.html"


class QuizView(View):
    def get(self, request):
        questions = Question.objects.all().order_by("number")
        options_dictionary = {}
        for question in questions:
            if question.type != "D":
                options_dictionary[question.number] = question.get_answer_options()
        return render(
            request,
            "quiz.html",
            {
                "questions": questions,
                "options_dictionary": options_dictionary,
            },
        )

    def post(self, request):
        # Save survey, lead and responses if req. met
        response_dict = dict(request.POST)

        for key in response_dict:
            # Convert lists into string text
            response_dict[key] = ", ".join(response_dict[key])
            if response_dict[key] is None or response_dict[key] == "":
                return JsonResponse(
                    {"response": "All fields required. Nice try!"},
                    status=400,
                )

        response_dict_keys = list(response_dict.keys())
        questions = Question.objects.all()
        email = response_dict["email"]

        try:
            lead = Lead.objects.create(email=email)
            survey = Survey.objects.create(lead=lead)
        except IntegrityError:
            return render(
                request,
                "error.html",
                {
                    "message": "You've already taken this survey, and we've mailed your Good Life Report!"
                },
                status=409,
            )

        for key in response_dict_keys:
            if key.isdigit():
                text = response_dict[key]
                for qn in questions:
                    if qn.number == int(key):
                        question = qn
                        Response(
                            survey=survey,
                            question=question,
                            text=text,
                        ).save()

        # Calculate and save lead score
        responses = Response.objects.filter(survey=survey).all()
        score = utils.calculate_score(responses)
        lead.score = score
        lead.save()

        print(score)

        # Generate pdf report
        report = utils.generate_report(questions, responses, email, score)

        # Mail the report
        utils.mail_report(report, email)

        return render(request, "thanks.html")


@staff_member_required
def analyze(request):
    # Analyze response percentages for each question into the results dictionary
    questions = Question.objects.exclude(type="D").order_by("number")
    results = {}

    for question in questions:
        responses = question.question_responses.all()
        answers = question.answers.all()
        answer_counts_dict = {}
        for answer in answers:
            answer_count = 0
            for response in responses:
                response_list = response.text.split(", ")
                if answer.text in response_list:
                    answer_count += 1
            answer_counts_dict[answer.text] = answer_count
        results[question.text] = answer_counts_dict

    # Generate pie charts using Plotly for each question
    charts = []
    for result in results:
        title = result
        data = {}
        labels = list(results[result].keys())
        values = list(results[result].values())
        data["labels"] = labels
        data["values"] = values
        trace = go.Pie(labels=data["labels"], values=data["values"], showlegend=True)
        layout = go.Layout(title=title, autosize=True)
        figure = go.Figure(data=[trace], layout=layout)
        figure.update_layout(
            title={
                "y": 1.0,
                "x": 0.5,
                "xanchor": "center",
                "yanchor": "top",
            },
            legend={
                "yanchor": "top",
                "y": -0.1,
                "xanchor": "center",
                "x": 0.5,
            },
        )
        charts.append(pyo.plot(figure, output_type="div"))

    return render(
        request,
        "insights.html",
        {
            "charts": charts,
        },
    )

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="description" content="{% block description %}{% endblock description %}">
        <title>{% block title %}{% endblock title %} - Leads</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>
    <body>
        {% block content %}{% endblock content %}
        {% block scripts %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        {% endblock scripts %}
    </body>
</html>

templates/error.html
{% extends "base.html" %}
{% load static %}

{% block description %}Take a short survey to win a $1000 coupon with us!{% endblock description %}

{% block title %}Thank you for taking the GLS!{% endblock title %}

{% block content %}
    <div class="container-fluid text-center min-vh-100 bg-light">
        <h1 class="text-dark pt-5">Oops!</h1>
        <p class="lead text-danger mt-3">{{ message }}</p>
    </div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block description %}Take a short survey to get your Good Life Report!{% endblock description %}

{% block title %}The Good Life Survey{% endblock title %}

{% block content %}
    <main>
        <div class="container-fluid">
            <div class="row vh-100 align-items-center text-center justify-content-center">
                <div class="col col-md-6">
                    <h1 class="text-dark">Welcome to the Good Life Survey!</h1>
                    <div class="card bg-light h-100 py-5">
                        <p class="lead px-2 pt-3 text-success">Take this survey and I'll mail you a Good Life Report to enhance your life!</p>
                        <p class="text-dark px-2">You will be asked about your problems in life, and we'll generate a Good Life Score based on your answers!</p>
                        <div class="row mx-auto mt-5">
                            <div class="col text-center">
                                <a href="{% url 'survey:quiz' %}" class="text-success fs-1">Begin</button> 
                            </div>
                        </div>
                    </div>           
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/insights.html
{% extends "admin/base.html" %}

{% block branding %}
    <h1>Survey Insights</h1>
{% endblock branding %}

{% block content %}
    <div class="container-fluid min-vh-100 bg-light">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        {% for chart in charts %}
                            <div style="margin: 50px auto; padding-top: 25px; border: 2px dotted lightblue;">
                                {{ chart|safe }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/quiz.html
{% extends "base.html" %}
{% load static %}

{% block description %}Take a short survey to get your Good Life Report!{% endblock description %}

{% block title %}The Good Life Survey{% endblock title %}

{% block content %}
    <main>
        <div class="container-fluid">
            <div class="row vh-100 align-items-center justify-content-center">
                <div class="col col-md-6">
                    <h1 class="text-dark text-center">Welcome to the $1000 survey!</h1>
                    <div class="card bg-light h-100 lead">
                        <form action="{% url 'survey:quiz' %}" method="post" id="survey-form">
                            {% csrf_token %}
                            <div id="question-container" class="p-3 p-md-5">
                                {% for question in questions %} 
                                    <div id="q-{{ question.number }}" class="question d-none">
                                        <p>
                                            <span class="bg-dark text-light rounded-5 px-2 py-1 me-2">{{ question.number }}</span>
                                            {{ question.text }}
                                        </p>
                                        {% if question.type == "D" %}
                                            <div id="a-{{ question.number }}">
                                                <input type="text" class="form-control" name="{{ question.number }}">
                                            </div>
                                        {% elif question.type == "S" %}
                                            {% for key, value in options_dictionary.items %}
                                                {% if key == question.number %}
                                                    <div id="a-{{ question.number }}" class="choices">
                                                        {% for option in value %}
                                                            <div class="form-check">
                                                                <input type="radio" class="form-check-input" name="{{ question.number }}" value="{{ option }}">
                                                                <label class="form-check-label">{{ option }}</label>
                                                            </div>
                                                        {% endfor %}
                                                    </div>           
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            {% for key, value in options_dictionary.items %}
                                                {% if key == question.number %}
                                                    <div id="a-{{ question.number }}" class="choices">
                                                        {% for option in value %}
                                                            <div class="form-check">
                                                                <input type="checkbox" class="form-check-input" name="{{ question.number }}" value="{{ option }}">
                                                                <label class="form-check-label">{{ option }}</label>
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                {% endfor %}
                                <div id="submit" class="row mx-auto d-none">
                                    <p class="lead text-center text-success">Enter your email to receive coupon</p>
                                    <input required type="email" class="form-control form-control-lg mb-3" name="email">
                                    <button type="submit" id="submit-button" class="btn btn-lg btn-success mx-auto">Get Your $1000</button>
                                </div>
                            </div>
                        </form>
                        <div id="survey-controls" class="my-3 row mx-auto">
                            <div class="col">
                                <button id="prev" class="btn btn-sm btn-dark">Back</button>
                            </div>
                            <div class="col">
                                <button id="next" class="btn btn-sm btn-dark">Next</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/quiz.js' %}"></script>
{% endblock scripts %}

templates/thanks.html
{% extends "base.html" %}
{% load static %}

{% block description %}Take a short survey to win a $1000 coupon with us!{% endblock description %}

{% block title %}Thank you for taking the GLS!{% endblock title %}

{% block content %}
    <div class="container-fluid text-center min-vh-100 bg-light">
        <h1 class="text-dark pt-5">Thank you for taking the Good Life Survey!</h1>
        <p class="lead text-info mt-3">Please check your inbox for the Good Life Report!</p>
        <p class="small text-success mt-5">Join the Good Life community today for enhancing your life!</p>
    </div>
{% endblock content %}